### ISSUE TITLE
Multiplayer Limit Remover - Not Working

### ISSUE THREAD

**Issue by Dealman** [sinai-dev/Hellpoint-Mods#1]
We have been unable to get this mod to work. Console does say;

`[Info   :   BepInEx] Loading [Multiplayer Limit Remover 2.0.0]`

But nothing else regarding the plugin. Is there a specific way we should join eachother? We've tried via the matchmaker, placing invites and match code. All 3 have BepInEx and the mod installed, yet receive the _"world is full"_ message.

**Comment by sinai-dev** [comment]
Hey, yeah sorry I think I released it a bit too early, don't think it's working at all yet. Was talking to someone who was helping me test it and work on it but they've disappeared at the moment, will continue working on it when I get a chance.

**Comment by ThumpieBunnyEve** [comment]
a lot of us over on discord.gg/hellpoint   are still watching this mod. waiting for you to resume work on it.  Were all just sitting around waiting to help bug test for you.  Don't feel like a stranger!

**Comment by sinai-dev** [comment]
@ThumpieBunnyEve good to know! Unfortunately I'm not really sure what else could be the problem, as far as I can tell all my patches are working as intended so there must be a piece I'm missing. At this point it might be worth asking the dev how exactly the multiplayer limit is enforced, other than in `NetworkCommunication_ClientAskForConnection` and `OnlineManager_StateUpdateAnswered`.

**Comment by sinai-dev** [comment]
Managed to get this "working", at least I was able to connect to a game with 3 players multiple times, its not perfect but its definitely working now.
